name: Integration Test

on:
  push:
    branches: [ "main", "ci-test" ]
  pull_request:
    branches: [ "main", "ci-test" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Setup BATS testing framework
      uses: mig4/setup-bats@v1.2.0
      with:
        bats-version: 1.2.1

    - name: Run test
      run: make -C test
