name: ShellCheck

on:
  push:
    branches: [ "main", "ci-test" ]
  pull_request:
    branches: [ "main", "ci-test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        additional_files: 'kubensenter mkWrapperDropin *.bats'
